### ISSUE TITLE
Comparison with wayland-proxy-virtwl

### ISSUE THREAD

**Issue by DemiMarie** [Supreeeme/xwayland-satellite#5]
How does this compare with Thomas Leonard’s [wayland-proxy-virtwl](https://github.com/talex5/wayland-proxy-virtwl)?

**Comment by Supreeeme** [comment]
I was not aware of that project before, but from a quick glance/trial run, besides being written in OCaml instead of Rust, wayland-proxy-virtwl seems a lot more featureful and focused on VMs than xwayland-satellite. xwayland-satellite doesn't do any sort of proxying of the compositor or provide support for stuff like virtio-gpu - it connects to the host compositor the same way any standard Wayland application would. wayland-proxy-virtwl's X11 support is also likely more mature. xwayland-satellite does support hardware acceleration through wl_drm/linux-dmabuf though, which wayland-proxy-virtwl does not appear to support.
